language: node_js
node_js:
  - 6
  - 7
cache:
  yarn: true
script:
  - yarn build-css
  - yarn flow -- check
  - yarn test -- --coverage
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
